# Generated by Django 5.2.1 on 2025-05-19 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('resultado', models.TextField()),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploracion.mision')),
            ],
        ),
        migrations.CreateModel(
            name='Astronauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=50)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploracion.mision')),
            ],
        ),
    ]
